#!/bin/bash

#1. Get the list of the network interfaces of the machine without displaying any detail for these interfaces. Only the list of names.

#ifconfig -l     ifconfig is deprecated.  ip is in place. 

ip a
