#!/bin/bash

#12. Figure out the exact size of each folder of /var in a humanly understandable way followed by the path of it.

du  -h /var/*

# -b shows bytes, -h shows human readable form.  ex. 1k, M, G)
