#!/bin/bash

#17. Find the command that allows you to connect via ssh on the VM.(In parallel with the graphic session)

#Iptables provides packet filtering, network address translation (NAT) and other packet mangling
#Two of the most common uses of iptables is to provide firewall support and NAT.

ssh usrname@remotehost

